-- Create billable_report table with wide format
-- Uses FK references to master_services, master_machinery, master_consumables
-- No redundant text name columns — those are resolved via the billable_report_with_names view
CREATE TABLE IF NOT EXISTS public.billable_report (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id INT8 NOT NULL,
  bill_id TEXT NOT NULL,
  uid TEXT NOT NULL,
  service_id INT8 REFERENCES public.master_services(id) ON DELETE SET NULL,
  machinery_id INT8 REFERENCES public.master_machinery(id) ON DELETE SET NULL,
  
  -- 14 consumable slots (FK IDs only — names resolved via view)
  consumable_1_id INT8 REFERENCES public.master_consumables(id) ON DELETE SET NULL,
  consumable_1_units NUMERIC,
  consumable_1_batch_id TEXT,
  consumable_2_id INT8 REFERENCES public.master_consumables(id) ON DELETE SET NULL,
  consumable_2_units NUMERIC,
  consumable_2_batch_id TEXT,
  consumable_3_id INT8 REFERENCES public.master_consumables(id) ON DELETE SET NULL,
  consumable_3_units NUMERIC,
  consumable_3_batch_id TEXT,
  consumable_4_id INT8 REFERENCES public.master_consumables(id) ON DELETE SET NULL,
  consumable_4_units NUMERIC,
  consumable_4_batch_id TEXT,
  consumable_5_id INT8 REFERENCES public.master_consumables(id) ON DELETE SET NULL,
  consumable_5_units NUMERIC,
  consumable_5_batch_id TEXT,
  consumable_6_id INT8 REFERENCES public.master_consumables(id) ON DELETE SET NULL,
  consumable_6_units NUMERIC,
  consumable_6_batch_id TEXT,
  consumable_7_id INT8 REFERENCES public.master_consumables(id) ON DELETE SET NULL,
  consumable_7_units NUMERIC,
  consumable_7_batch_id TEXT,
  consumable_8_id INT8 REFERENCES public.master_consumables(id) ON DELETE SET NULL,
  consumable_8_units NUMERIC,
  consumable_8_batch_id TEXT,
  consumable_9_id INT8 REFERENCES public.master_consumables(id) ON DELETE SET NULL,
  consumable_9_units NUMERIC,
  consumable_9_batch_id TEXT,
  consumable_10_id INT8 REFERENCES public.master_consumables(id) ON DELETE SET NULL,
  consumable_10_units NUMERIC,
  consumable_10_batch_id TEXT,
  consumable_11_id INT8 REFERENCES public.master_consumables(id) ON DELETE SET NULL,
  consumable_11_units NUMERIC,
  consumable_11_batch_id TEXT,
  consumable_12_id INT8 REFERENCES public.master_consumables(id) ON DELETE SET NULL,
  consumable_12_units NUMERIC,
  consumable_12_batch_id TEXT,
  consumable_13_id INT8 REFERENCES public.master_consumables(id) ON DELETE SET NULL,
  consumable_13_units NUMERIC,
  consumable_13_batch_id TEXT,
  consumable_14_id INT8 REFERENCES public.master_consumables(id) ON DELETE SET NULL,
  consumable_14_units NUMERIC,
  consumable_14_batch_id TEXT,
  
  report_date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for fast queries
CREATE INDEX IF NOT EXISTS idx_billable_report_branch ON public.billable_report(branch_id);
CREATE INDEX IF NOT EXISTS idx_billable_report_bill ON public.billable_report(bill_id);
CREATE INDEX IF NOT EXISTS idx_billable_report_service ON public.billable_report(service_id);
CREATE INDEX IF NOT EXISTS idx_billable_report_machinery ON public.billable_report(machinery_id);

-- Disable RLS for now (enable later with proper policies)
ALTER TABLE public.billable_report DISABLE ROW LEVEL SECURITY;

-- View that resolves FK IDs to human-readable names & cost for reports
CREATE OR REPLACE VIEW public.billable_report_with_names AS
SELECT
  br.id,
  br.branch_id,
  br.bill_id,
  br.uid,
  br.report_date,
  br.service_id,
  ms.service_name,
  br.machinery_id,
  mm.machine_name,
  br.consumable_1_id,
  mc1.consumable_name AS consumable_1_name,
  br.consumable_1_units,
  COALESCE(mc1.cost_unit, 0) AS consumable_1_cost_unit,
  (br.consumable_1_units * COALESCE(mc1.cost_unit, 0)) AS consumable_1_cost,
  br.consumable_1_batch_id,
  br.consumable_2_id,
  mc2.consumable_name AS consumable_2_name,
  br.consumable_2_units,
  COALESCE(mc2.cost_unit, 0) AS consumable_2_cost_unit,
  (br.consumable_2_units * COALESCE(mc2.cost_unit, 0)) AS consumable_2_cost,
  br.consumable_2_batch_id,
  br.consumable_3_id,
  mc3.consumable_name AS consumable_3_name,
  br.consumable_3_units,
  COALESCE(mc3.cost_unit, 0) AS consumable_3_cost_unit,
  (br.consumable_3_units * COALESCE(mc3.cost_unit, 0)) AS consumable_3_cost,
  br.consumable_3_batch_id,
  br.consumable_4_id,
  mc4.consumable_name AS consumable_4_name,
  br.consumable_4_units,
  COALESCE(mc4.cost_unit, 0) AS consumable_4_cost_unit,
  (br.consumable_4_units * COALESCE(mc4.cost_unit, 0)) AS consumable_4_cost,
  br.consumable_4_batch_id,
  br.consumable_5_id,
  mc5.consumable_name AS consumable_5_name,
  br.consumable_5_units,
  COALESCE(mc5.cost_unit, 0) AS consumable_5_cost_unit,
  (br.consumable_5_units * COALESCE(mc5.cost_unit, 0)) AS consumable_5_cost,
  br.consumable_5_batch_id,
  br.consumable_6_id,
  mc6.consumable_name AS consumable_6_name,
  br.consumable_6_units,
  COALESCE(mc6.cost_unit, 0) AS consumable_6_cost_unit,
  (br.consumable_6_units * COALESCE(mc6.cost_unit, 0)) AS consumable_6_cost,
  br.consumable_6_batch_id,
  br.consumable_7_id,
  mc7.consumable_name AS consumable_7_name,
  br.consumable_7_units,
  COALESCE(mc7.cost_unit, 0) AS consumable_7_cost_unit,
  (br.consumable_7_units * COALESCE(mc7.cost_unit, 0)) AS consumable_7_cost,
  br.consumable_7_batch_id,
  br.consumable_8_id,
  mc8.consumable_name AS consumable_8_name,
  br.consumable_8_units,
  COALESCE(mc8.cost_unit, 0) AS consumable_8_cost_unit,
  (br.consumable_8_units * COALESCE(mc8.cost_unit, 0)) AS consumable_8_cost,
  br.consumable_8_batch_id,
  br.consumable_9_id,
  mc9.consumable_name AS consumable_9_name,
  br.consumable_9_units,
  COALESCE(mc9.cost_unit, 0) AS consumable_9_cost_unit,
  (br.consumable_9_units * COALESCE(mc9.cost_unit, 0)) AS consumable_9_cost,
  br.consumable_9_batch_id,
  br.consumable_10_id,
  mc10.consumable_name AS consumable_10_name,
  br.consumable_10_units,
  COALESCE(mc10.cost_unit, 0) AS consumable_10_cost_unit,
  (br.consumable_10_units * COALESCE(mc10.cost_unit, 0)) AS consumable_10_cost,
  br.consumable_10_batch_id,
  br.consumable_11_id,
  mc11.consumable_name AS consumable_11_name,
  br.consumable_11_units,
  COALESCE(mc11.cost_unit, 0) AS consumable_11_cost_unit,
  (br.consumable_11_units * COALESCE(mc11.cost_unit, 0)) AS consumable_11_cost,
  br.consumable_11_batch_id,
  br.consumable_12_id,
  mc12.consumable_name AS consumable_12_name,
  br.consumable_12_units,
  COALESCE(mc12.cost_unit, 0) AS consumable_12_cost_unit,
  (br.consumable_12_units * COALESCE(mc12.cost_unit, 0)) AS consumable_12_cost,
  br.consumable_12_batch_id,
  br.consumable_13_id,
  mc13.consumable_name AS consumable_13_name,
  br.consumable_13_units,
  COALESCE(mc13.cost_unit, 0) AS consumable_13_cost_unit,
  (br.consumable_13_units * COALESCE(mc13.cost_unit, 0)) AS consumable_13_cost,
  br.consumable_13_batch_id,
  br.consumable_14_id,
  mc14.consumable_name AS consumable_14_name,
  br.consumable_14_units,
  COALESCE(mc14.cost_unit, 0) AS consumable_14_cost_unit,
  (br.consumable_14_units * COALESCE(mc14.cost_unit, 0)) AS consumable_14_cost,
  br.consumable_14_batch_id,
  br.created_at,
  br.updated_at
FROM public.billable_report br
LEFT JOIN public.master_services ms ON br.service_id = ms.id
LEFT JOIN public.master_machinery mm ON br.machinery_id = mm.id
LEFT JOIN public.master_consumables mc1 ON br.consumable_1_id = mc1.id
LEFT JOIN public.master_consumables mc2 ON br.consumable_2_id = mc2.id
LEFT JOIN public.master_consumables mc3 ON br.consumable_3_id = mc3.id
LEFT JOIN public.master_consumables mc4 ON br.consumable_4_id = mc4.id
LEFT JOIN public.master_consumables mc5 ON br.consumable_5_id = mc5.id
LEFT JOIN public.master_consumables mc6 ON br.consumable_6_id = mc6.id
LEFT JOIN public.master_consumables mc7 ON br.consumable_7_id = mc7.id
LEFT JOIN public.master_consumables mc8 ON br.consumable_8_id = mc8.id
LEFT JOIN public.master_consumables mc9 ON br.consumable_9_id = mc9.id
LEFT JOIN public.master_consumables mc10 ON br.consumable_10_id = mc10.id
LEFT JOIN public.master_consumables mc11 ON br.consumable_11_id = mc11.id
LEFT JOIN public.master_consumables mc12 ON br.consumable_12_id = mc12.id
LEFT JOIN public.master_consumables mc13 ON br.consumable_13_id = mc13.id
LEFT JOIN public.master_consumables mc14 ON br.consumable_14_id = mc14.id;
